#!/usr/bin/env python3
"""
Auto-README Generator - No config needed!
Uses project analysis to automatically generate README
"""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

from gitsage.utils import ProjectDetector

def auto_generate_readme(output_path="output/README/AUTO-GENERATED-README.md"):
    """
    Auto-generate README from project analysis
    No config file needed!
    """

    print("\n" + "="*60)
    print("  Auto README Generator - Zero Config!")
    print("="*60 + "\n")

    # Analyze project
    print("[1/3] Analyzing project...")
    detector = ProjectDetector()
    detection = detector.detect()

    print(f"  Detected: {detection.get('type', 'unknown')} project")
    print(f"  Language: {detection.get('primary_language', 'unknown')}")

    # Generate README content
    print("\n[2/3] Generating README...")

    project_name = Path.cwd().name
    project_type = detection.get('type', 'software')
    language = detection.get('primary_language', 'Python')
    framework = detection.get('framework', '')

    readme_content = f"""# {project_name}

> Auto-generated README by GitSage

## Overview

A {language}{' ' + framework if framework else ''} {project_type} project.

## Features

- Modern {language} implementation
{f'- Built with {framework}' if framework else ''}
- Well-structured codebase
- Ready for development

## Installation

```bash
# Clone the repository
git clone https://github.com/yourusername/{project_name}.git
cd {project_name}

# Install dependencies
pip install -r requirements.txt  # For Python projects
# or npm install                 # For Node.js projects
```

## Usage

```bash
# Run the project
python main.py  # Adjust based on your entry point
```

## Project Structure

```
{project_name}/
├── src/           # Source code
├── tests/         # Test files
├── docs/          # Documentation
└── README.md      # This file
```

## Development

### Prerequisites

- {language} (version as specified in project)
{f'- {framework}' if framework else ''}

### Setup

1. Clone the repository
2. Install dependencies
3. Run tests
4. Start developing!

## Contributing

Contributions are welcome! Please:

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Submit a pull request

## License

MIT License - See LICENSE file for details

## Contact

For questions or support, please open an issue.

---

*This README was auto-generated by GitSage. Edit as needed!*
"""

    # Write to file
    print(f"\n[3/3] Writing to {output_path}...")
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(readme_content)

    print(f"\n✅ README generated successfully!")
    print(f"   Location: {output_path}")
    print(f"   Size: {len(readme_content)} bytes")
    print(f"\n   Review and edit as needed!")

    return output_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Auto-generate README from project analysis')
    parser.add_argument('--output', '-o', default='output/README/AUTO-GENERATED-README.md',
                       help='Output file path')

    args = parser.parse_args()

    auto_generate_readme(args.output)
